### Academic Years ###
GET http://127.0.0.1:5000/api/v1/academic_years
Content-Type: application/json

###
GET http://127.0.0.1:5000/api/v1/academic_years/0fd6ebb5-fce3-433f-afc6-effe60c708e9
Content-Type: application/json

###
POST http://127.0.0.1:5000/api/v1/academic_years
Content-Type: application/json

{
    "label": "2027"
}



### Periodes ###
GET http://127.0.0.1:5000/api/v1/periodes
Content-Type: application/json

###
GET http://127.0.0.1:5000/api/v1/periodes/22e46e6b-c4ce-41b6-bf14-e901c5819bd7
Content-Type: application/json

###
POST http://127.0.0.1:5000/api/v1/periodes
Content-Type: application/json

{
    "label": "2029 - 2032",
    "desc": "Angkatan IV"
}

###
PUT http://127.0.0.1:5000/api/v1/periodes/3eda18ff-ff34-4a1a-90c8-d362120b49a9
Content-Type: application/json

{
    "label": "2032 - 2035",
    "desc": "Angkatan IV"
}

###
DELETE http://127.0.0.1:5000/api/v1/periodes/3eda18ff-ff34-4a1a-90c8-d362120b49a9
Content-Type: application/json
