default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: imin
  password: admin
  host: localhost
  port: 5432
development:
  <<: *default
  database: academic_server_development
test:
  <<: *default
  database: academic_server_test
production:
  <<: *default
  database: academic_server_production
  username: academic_server
  password: <%= ENV["ACADEMIC_SERVER_DATABASE_PASSWORD"] %>
